language: ruby
rvm:
  - "2.0.0"

notifications:
  email:
    - pgf8@case.edu
    - mma29@case.edu

script:
  - bundle exec rake db:reset
  - bundle exec rake

before_script:
  - cp config/database.yml.sample config/database.yml
  - cp config/fedora.yml.sample config/fedora.yml
  - cp config/solr.yml.sample config/solr.yml
  - cp config/redis.yml.sample config/redis.yml
  - cp config/devise.yml.sample config/devise.yml
  - cp config/initializers/secret_token.rb.sample config/initializers/secret_token.rb

before_install:
  - sudo mkdir -p /opt/install
  - sudo wget -P /opt/install http://fits.googlecode.com/files/fits-0.6.2.zip
  - sudo unzip /opt/install/fits-0.6.2.zip -d /opt/install
  - sudo chmod +x /opt/install/fits-0.6.2/fits.sh
  - sudo cp -r /opt/install/fits-0.6.2/* /usr/local/bin/
  - sudo ln -s /usr/local/bin/fits.sh /usr/local/bin/fits

services:
  - redis-server
